export const ApiErrorCodes = {
  // --- General/System Errors ---
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE', // e.g., third-party service down
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  BAD_REQUEST: 'BAD_REQUEST', // Generic client-side error
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED', // API endpoint not yet implemented

  // --- Authentication & Authorization Errors ---
  UNAUTHORIZED: 'UNAUTHORIZED', // General authentication failure (e.g., missing token)
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED', // User needs to authenticate
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
  MISSING_TOKEN: 'MISSING_TOKEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED', // User authenticated but lacks specific permission
  FORBIDDEN: 'FORBIDDEN', // Synonymous with PERMISSION_DENIED or generally no access
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  MFA_REQUIRED: 'MFA_REQUIRED', // Multi-factor authentication required
  MFA_FAILED: 'MFA_FAILED',

  // --- User Management Errors ---
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH', // During password confirmation
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_USERNAME_FORMAT: 'INVALID_USERNAME_FORMAT',
  USER_REGISTRATION_FAILED: 'USER_REGISTRATION_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
  ACCOUNT_VERIFICATION_REQUIRED: 'ACCOUNT_VERIFICATION_REQUIRED',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',

  // --- Resource & Data Errors ---
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  INVALID_RESOURCE_ID: 'INVALID_RESOURCE_ID',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED', // e.g., another user editing
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT', // Generic conflict, e.g., race condition or unique constraint violation
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED', // Specific field validation errors
  INVALID_INPUT: 'INVALID_INPUT', // More generic input validation error
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FIELD_VALUE: 'INVALID_FIELD_VALUE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS', // Rate limiting
  DATA_INTEGRITY_VIOLATION: 'DATA_INTEGRITY_VIOLATION',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND', // More specific than RESOURCE_NOT_FOUND for database records
  RECORD_UPDATE_FAILED: 'RECORD_UPDATE_FAILED',
  RECORD_CREATION_FAILED: 'RECORD_CREATION_FAILED',
  RECORD_DELETION_FAILED: 'RECORD_DELETION_FAILED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION', // e.g., trying to cancel an already cancelled order

  // --- File & Upload Errors ---
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  FILE_CORRUPTED: 'FILE_CORRUPTED',

  // --- Payment & Billing Errors ---
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  TRANSACTION_DECLINED: 'TRANSACTION_DECLINED',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  CARD_EXPIRED: 'CARD_EXPIRED',
  INVALID_CARD_DETAILS: 'INVALID_CARD_DETAILS',
  BILLING_INFORMATION_MISSING: 'BILLING_INFORMATION_MISSING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',

  // --- External Service & Integration Errors ---
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR', // Catch-all for external service issues
  THIRD_PARTY_API_ERROR: 'THIRD_PARTY_API_ERROR',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  GEOCODING_FAILED: 'GEOCODING_FAILED',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',

  // --- Business Logic Errors ---
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
  ITEM_OUT_OF_STOCK: 'ITEM_OUT_OF_STOCK',
  CART_EMPTY: 'CART_EMPTY',
  INVALID_PROMO_CODE: 'INVALID_PROMO_CODE',
  PROMO_CODE_EXPIRED: 'PROMO_CODE_EXPIRED',
  MINIMUM_ORDER_AMOUNT_NOT_MET: 'MINIMUM_ORDER_AMOUNT_NOT_MET',
  MAXIMUM_LIMIT_EXCEEDED: 'MAXIMUM_LIMIT_EXCEEDED', // e.g., max items in cart, max attempts
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION', // Generic for when a business rule isn't met

  // --- Search & Filtering Errors ---
  INVALID_SEARCH_QUERY: 'INVALID_SEARCH_QUERY',
  INVALID_SORT_PARAMETER: 'INVALID_SORT_PARAMETER',
  INVALID_FILTER_PARAMETER: 'INVALID_FILTER_PARAMETER',
  NO_SEARCH_RESULTS: 'NO_SEARCH_RESULTS',

  // --- Organisations Errors ---
  ORGANISATION_NOT_FOUND: 'ORGANISATION_NOT_FOUND',
} as const;

export type ApiErrorCode = (typeof ApiErrorCodes)[keyof typeof ApiErrorCodes];
